// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT username, role, password_hash, id FROM users
WHERE id=$1
`

type GetUserByIDRow struct {
	Username     string
	Role         string
	PasswordHash string
	ID           pgtype.UUID
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.ID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, role, password_hash, id FROM users
WHERE username=$1
`

type GetUserByUsernameRow struct {
	Username     string
	Role         string
	PasswordHash string
	ID           pgtype.UUID
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.ID,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users(password_hash, username)
VALUES ($1, $2)
RETURNING id
`

type InsertUserParams struct {
	PasswordHash string
	Username     string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.PasswordHash, arg.Username)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const setRole = `-- name: SetRole :exec
UPDATE users 
SET role=$1
WHERE id=$2
`

type SetRoleParams struct {
	Role string
	ID   pgtype.UUID
}

func (q *Queries) SetRole(ctx context.Context, arg SetRoleParams) error {
	_, err := q.db.Exec(ctx, setRole, arg.Role, arg.ID)
	return err
}
